
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.AnalizadorArchivoRp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_PLANETA_SALIDA = 34;
  public static final int PR_SIZE = 8;
  public static final int PR_FINALIZACION = 16;
  public static final int TIPO = 45;
  public static final int ENTERO = 43;
  public static final int DOUBLE = 44;
  public static final int CORCHETE_C = 25;
  public static final int CORCHETE_A = 24;
  public static final int LLAVE_C = 23;
  public static final int PR_ID = 7;
  public static final int SEPARADOR = 27;
  public static final int LLAVE_A = 22;
  public static final int PR_ACCIONES = 36;
  public static final int PR_PLANETAS_NEUTRALES = 4;
  public static final int PR_TURNO_SALIDA = 32;
  public static final int PR_COLUMNAS = 10;
  public static final int PR_TURNO_LLEGADA = 33;
  public static final int PR_PORCENTAJE_MUERTES = 19;
  public static final int PR_FILAS = 9;
  public static final int PR_PLANETA_DESTINO = 35;
  public static final int ID = 42;
  public static final int PR_CONQUISTADOR = 37;
  public static final int PR_JUGADORES = 5;
  public static final int BOOLEAN = 41;
  public static final int PR_NAVES = 17;
  public static final int EOF = 0;
  public static final int PR_MAPA_CIEGO = 13;
  public static final int PR_ACUMULAR = 14;
  public static final int error = 1;
  public static final int COMILLA = 28;
  public static final int PR_PLANETAS = 6;
  public static final int PR_PRODUCCION = 18;
  public static final int PR_TIPO = 21;
  public static final int PR_TURNO = 31;
  public static final int ASIGNACION = 26;
  public static final int PR_AZAR = 11;
  public static final int PR_POSICION_Y = 39;
  public static final int PR_JUGADOR = 40;
  public static final int PR_POSICION_X = 38;
  public static final int PR_MOSTRAR_NAVES = 29;
  public static final int PR_MOSTRAR_ESTADISTICAS = 30;
  public static final int PR_MAPA = 3;
  public static final int PR_CANTIDAD_PLANETAS_NEUTRALES = 12;
  public static final int PR_NOMBRE = 2;
  public static final int PR_PLANETAS_JUGADORES = 20;
  public static final int PR_NEUTRALES = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_NOMBRE",
  "PR_MAPA",
  "PR_PLANETAS_NEUTRALES",
  "PR_JUGADORES",
  "PR_PLANETAS",
  "PR_ID",
  "PR_SIZE",
  "PR_FILAS",
  "PR_COLUMNAS",
  "PR_AZAR",
  "PR_CANTIDAD_PLANETAS_NEUTRALES",
  "PR_MAPA_CIEGO",
  "PR_ACUMULAR",
  "PR_NEUTRALES",
  "PR_FINALIZACION",
  "PR_NAVES",
  "PR_PRODUCCION",
  "PR_PORCENTAJE_MUERTES",
  "PR_PLANETAS_JUGADORES",
  "PR_TIPO",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "ASIGNACION",
  "SEPARADOR",
  "COMILLA",
  "PR_MOSTRAR_NAVES",
  "PR_MOSTRAR_ESTADISTICAS",
  "PR_TURNO",
  "PR_TURNO_SALIDA",
  "PR_TURNO_LLEGADA",
  "PR_PLANETA_SALIDA",
  "PR_PLANETA_DESTINO",
  "PR_ACCIONES",
  "PR_CONQUISTADOR",
  "PR_POSICION_X",
  "PR_POSICION_Y",
  "PR_JUGADOR",
  "BOOLEAN",
  "ID",
  "ENTERO",
  "DOUBLE",
  "TIPO"
  };
}

